phase2_start_service_processes() called -- currently a NOP
phase3_start_service_processes() called -- currently a NOP
phase4_start_service_processes() called -- currently a NOP
phase5_start_service_processes() called -- currently a NOP
testcase_main(): started
QUICK SUMMARY: TODO
XXp1(): creating children
XXp2(): started, pid = 4, calling blockMe
XXp2(): started, pid = 5, calling blockMe
XXp2(): started, pid = 6, calling blockMe
XXp1(): creating zapper children
XXp3(): started, pid = 7, calling zap on pid 4
XXp4(): started, pid = 8, calling zap on pid 6
XXp1(): unblocking children
<<<<<<< HEAD
=======
XXp2(): pid = 4, after blockMe
XXp2(): pid = 4
XXp3(): after call to zap
XXp2(): pid = 5, after blockMe
XXp2(): pid = 5
XXp2(): pid = 6, after blockMe
XXp2(): pid = 6
XXp4(): after call to zap
XXp1(): after unblocking 4, result = 0
XXp1(): after unblocking 5, result = 0
XXp1(): after unblocking 6, result = 0
ERROR: Process pid 3 called quit() while it still had children.
finish(): The simulation is now terminating.
>>>>>>> 32366c61001de33deffdb779381ff73c64253e00
