phase2_start_service_processes() called -- currently a NOP
phase3_start_service_processes() called -- currently a NOP
phase4_start_service_processes() called -- currently a NOP
phase5_start_service_processes() called -- currently a NOP
testcase_main(): started
testcase_main(): after fork of child 3
testcase_main(): performing first join
XXp1(): started
XXp1(): arg = 'XXp1'
XXp1(): zapping myself, should fail.  Calling zap(3)
ERROR: Attempt to zap() itself.
finish(): The simulation is now terminating.
